learup/urls.py
from django.contrib import admin
from django.urls import include, path

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name='index'),
    path('detail_employ/<int:employ_id>/', views.detail_employ, name='detail employ'),
    path('crear_empleado/', views.crear_empleado, name='crear empleado'),
    path('listar_jerarquia/', views.listar_jerarquias, name='listar jerarquia'),
    path('cambiar_jerarquia/', views.cambiar_jerarquias, name='cambiar jerarquia'),
]

app/models.py
# app/models.py
from django.db import models
from django.utils import timezone


class Jerarquia(models.Model):
    jerarquia = models.CharField(max_length=255)
    area = models.CharField(max_length=20, default='')

class Empleado(models.Model):
    nombre = models.CharField(max_length=255)
    correo = models.EmailField()
    telefono = models.CharField(max_length=20)
    area = models.CharField(max_length=20, default='')
    created_at = models.DateTimeField(default=timezone.now)
    estado = models.BooleanField(default=True)


class LogJerarquia(models.Model):
    id_empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    id_jerarquia = models.ForeignKey(Jerarquia, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    estado = models.BooleanField(default=True)

app/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['nombre', 'correo', 'telefono', 'area']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

app/views.py
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .forms import EmpleadoForm
from .models import Empleado, Jerarquia, LogJerarquia
from .serializers import EmpleadoSerializer


def crear_empleado(request):
    if request.method == 'POST':
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            empleado = form.save()
            jerarquia_id = request.POST.get('jerarquia')
            if jerarquia_id!='Seleccione...':
                jerarquia = Jerarquia.objects.get(id=jerarquia_id)
                LogJerarquia.objects.create(
                    id_empleado=empleado,
                    id_jerarquia=jerarquia
                )
            return redirect('/')

    form = EmpleadoForm()
    hierarchy = Jerarquia.objects.all()

    return render(request, 'crear_empleado.html', {'form': form, 'hierarchys': hierarchy})


def listar_jerarquias(request):
    hierarchy = Jerarquia.objects.all()
    return render(request, 'hierarchy_list.html', {'hierarchys': hierarchy})


def cambiar_jerarquias(request):
    if request.method == 'POST':
        hierarchy_id = request.POST.get('hierarchy')
        employ_id = request.POST.get('employ_id')
        log_jerarquia_exists = LogJerarquia.objects.filter(id_empleado=employ_id, estado=True).exists()
        if log_jerarquia_exists:
            log_jerarquia = LogJerarquia.objects.get(id_empleado=employ_id, estado=True)
            if log_jerarquia.id_jerarquia.id != int(hierarchy_id):
                employ = Empleado.objects.get(id=employ_id)
                hierarchy = Jerarquia.objects.get(id=hierarchy_id)
                LogJerarquia.objects.create(
                    id_empleado=employ,
                    id_jerarquia=hierarchy,
                    estado=True
                )
                log_jerarquia.estado = False
                log_jerarquia.save()
                return HttpResponse(f'<p class="success">Jerarquía cambiada exitosamente.</p>')
            return HttpResponse(f'<p class="warning">La jerarquía seleccionada es la misma que la actual.</p>')

        employ = Empleado.objects.get(id=employ_id)
        hierarchy = Jerarquia.objects.get(id=hierarchy_id)
        LogJerarquia.objects.create(
            id_empleado=employ,
            id_jerarquia=hierarchy,
            estado=True
        )
        return HttpResponse(f'<p class="success">Jerarquía cambiada exitosamente.</p>')


def detail_employ(request, employ_id):
    jefe="Sin Jefe"
    employ_list = []
    try:
        employ = get_object_or_404(Empleado, id=employ_id)
    except Exception: 
        employ = None

    try:
        log_jerarquia = LogJerarquia.objects.get(id_empleado=employ.id, estado=True)

        employ_list = Empleado.objects.filter(
            logjerarquia__id_jerarquia__lt=log_jerarquia.id_jerarquia,
            logjerarquia__estado=True
        )
        jefe_jerarquia = log_jerarquia.id_jerarquia.id + 1
        jefe = Empleado.objects.filter(logjerarquia__id_jerarquia=jefe_jerarquia, logjerarquia__estado=True).first()
        nom_jefe= jefe.nombre
    except Exception:
        nom_jefe= jefe

    hierarchy = Jerarquia.objects.all()
    return render(request, 'details.html', {
                      'employ': employ, 
                      'nom_jefe': nom_jefe, 
                      'employ_list': employ_list, 
                      'employ_hierarchys': log_jerarquia.id_jerarquia.jerarquia, 
                      'hierarchys': hierarchy
                      }
                  )

def index(request):
    employs = Empleado.objects.all()
    employ_details = []

    for employ in employs:
        try:
            log_jerarquia = LogJerarquia.objects.get(id_empleado=employ.id, estado=True)
            jerarquia_nombre = log_jerarquia.id_jerarquia.jerarquia
        except LogJerarquia.DoesNotExist:
            jerarquia_nombre = 'Sin Jerarquía'

        employ_details.append({
            'id': employ.id,
            'nombre': employ.nombre,
            'correo': employ.correo,
            'telefono': employ.telefono,
            'jerarquia_nombre': jerarquia_nombre,
            'estado': employ.estado,
        })

    return render(request, 'list_employees.html', {'employs': employ_details})

templates/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <link rel="stylesheet" href="{% static 'css/cover.css' %}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
            border-radius: 10px;
            /* Ajusta el valor según tus preferencias */
            overflow: hidden;
            /* Esto asegura que las esquinas redondeadas se muestren correctamente */
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body class="d-flex h-100 text-center text-white bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0">Cogen Tech</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                    <a class="nav-link" aria-current="page" href="{% url 'crear empleado' %}">Crear empleado</a>
                    <a class="nav-link" href="{% url 'listar jerarquia' %}">Lista Jerarquias</a>
                </nav>
            </div>
        </header>

        <main class="px-3">
            {% block content %}{% endblock %}
        </main>

        <footer class="mt-auto text-white-50">
            <p>Test project for <a href="https://www.cogentech.net" class="text-white">Cogen Tech</a>, by <a
                    href="https://api.whatsapp.com/send?phone=573212252231" class="text-white">Jhon Bohorquez</a>.</p>
        </footer>
    </div>

</body>

</html>

templates/crear_empleado.html
{% extends 'base.html' %}

{% block content %}
<h2>Crear Empleado</h2>

<form method="post" action="{% url 'crear empleado' %}">
    {% csrf_token %}

    <div class="mb-3">
        <label for="{{ form.nombre.id_for_label }}" class="form-label">Nombre:</label>
        {{ form.nombre }}
    </div>
    <div class="mb-3">
        <label for="{{ form.correo.id_for_label }}" class="form-label">Correo:</label>
        {{ form.correo }}
    </div>
    <div class="mb-3">
        <label for="{{ form.telefono.id_for_label }}" class="form-label">Teléfono:</label>
        {{ form.telefono }}
    </div>
    <div class="mb-3">
        <label for="{{ form.area.id_for_label }}" class="form-label">Área:</label>
        {{ form.area }}
    </div>

    <div class="mb-3">
        <label for="selectJerarquia" class="form-label">Jerarquía:</label>
        <select class="form-select" name="jerarquia" id="selectJerarquia" aria-label="Selecciona la jerarquía">
            <option selected disabled>Seleccione...</option>
            {% for hierarchy in hierarchys %}
            <option value="{{ hierarchy.id }}">{{ hierarchy.jerarquia }}</option>
            {% endfor %}
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/details.html
{% extends 'base.html' %}

{% block content %}
<div class="card text-center">

    {% if employ == Null %}

    <p></p>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                    <use xlink:href="#exclamation-triangle-fill" />
                </svg>
                <div>
                    No existe el registro o el empleado
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>


    {% else %}
    <div class="card-header text-muted">
        <h3>Detalles del empleado</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="card-body text-start">

                    <h5 class="card-title text-muted">{{ employ.nombre }}</h5>
                    <p class="text-muted">ID: {{ employ.id }}</p>
                    <p class="text-muted">Correo: {{ employ.correo }}</p>
                    <p class="text-muted">Teléfono: {{ employ.telefono }}</p>
                    {% if employ.logjerarquia_set.first %}
                    <p class="text-muted">Jerarquía: {{ employ_hierarchys }}
                    </p>
                    {% else %}
                    <p class="text-muted">Sin Jerarquía</p>
                    {% endif %}
                    <p class="card-text text-muted">Estado: {{ employ.estado }}</p>
                    <p class="card-text text-muted">Creado el: {{ employ.created_at|date:"F j, Y H:i" }}</p>
                </div>
            </div>
            <div class="col-sm-6">
                <h5 class="card-title text-muted">Jefe Directo: {{ nom_jefe }}</h5>
                <p></p>
                <h5 class="card-title text-muted">Empleados a cargo</h5>

                {% for one_employ in employ_list %}
                <p class="text-muted">{{ one_employ.nombre }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="card-footer text-muted">
        <form method="post" action="{% url 'cambiar jerarquia' %}" id="cambiarJerarquiaForm">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="mb-3">
                <h5 class="card-title text-muted">Cambiar Jerarquía:</h5>
                <select required class="form-select" name="hierarchy" id="selectJerarquia"
                    aria-label="Selecciona la jerarquía">
                    <option value="" disabled selected>Seleccione...</option>
                    {% for hierarchy in hierarchys %}
                    <option value="{{ hierarchy.id }}">{{ hierarchy.jerarquia }}</option>
                    {% endfor %}
                </select>
                <input type="hidden" name="employ_id" value="{{ employ.id }}">
            </div>
            <button type="button" class="btn btn-primary" id="guardarBtn">Guardar</button>
        </form>
        <div id="messages"></div>
    </div>
    {% endif %}
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#guardarBtn').click(function () {
            var url = $('#cambiarJerarquiaForm').attr('action');
            var formData = $('#cambiarJerarquiaForm').serialize();

            $.ajax({
                type: 'POST',
                url: url,
                data: formData,
                success: function (data) {
                    $('#messages').html(data);
                },
                error: function (data) {
                    console.log('Error:', data);
                },
            });
        });
    });
</script>

{% endblock %}

templates/hierarchy_list.html
<!-- detalle_empleado.html -->
{% extends 'base.html' %}

{% block content %}
<div class="card text-center">


    <div class="card-header text-muted">
        <h3>Lista de Jerarquias</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="card-body text-start">
                    {% for hierarchy in hierarchys %}
                    <p class="text-muted">{{ hierarchy.jerarquia }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/list_employees.html
{% extends 'base.html' %}

{% block content %}
<h1>Detalles del Empleado</h1>
<table class="table">
    <thead class="table-light">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Teléfono</th>
            <th>Jerarquía</th>
            <th>Estado</th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody class="table-light">
        {% for employ in employs %}
        <tr>
            <td>{{ employ.id }}</td>
            <td>{{ employ.nombre }}</td>
            <td>{{ employ.correo }}</td>
            <td>{{ employ.telefono }}</td>
            <td>{{ employ.jerarquia_nombre }}</td>
            <td>{{ employ.estado }}</td>
            <td><a href="{% url 'detail employ' employ.id %}">Ver</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}